name: togethertest
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  shared_preferences: ^2.0.6
  image_picker: ^0.8.0
  percent_indicator: ^4.2.3
  lottie: ^2.0.0
  provider: ^6.0.5
  file_picker: ^4.4.0
  url_launcher: ^6.1.5
  path_provider: ^2.0.2
  open_file: ^3.2.1
  dio: ^4.0.0
  http_parser: ^4.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/check.json
    - assets/basura.json
    - assets/like.json
    - assets/images/logo_nom.png
    - assets/images/logo_sol.png

